### ISSUE TITLE
No checkmark.png referenced in iOS7.less

### ISSUE THREAD

**Issue by choyongjoon** [sahat/hackathon-starter#56]
I found that radio buttons in 'My Account' page  are not shown correctly. 
In ios7.less, the theme uses '../../img/checkmark.png' but the file is not in there.

ios7.less line 789~792

``` css
input[type="checkbox"]:checked + span:before {
  background: #007aff url("../../img/checkmark.png") no-repeat center center;
  border-color: #007aff;
}
```
